name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')  # Check if commit message contains [build]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Updated to v4
      
    - name: Install dependencies
      run: npm install

    - name: Build project with Gulp
      run: npx gulp build  # Replace 'build' with your Gulp task name if different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Updated to v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Adjust this to your build output directory
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'
        create_branch: true
